### ISSUE TITLE
[QUESTION]Multi-node multi-gpu training

### ISSUE THREAD

**Issue by RickMeow** [OpenLMLab/collie#110]
Hello, I am currently fine-tuning a Llama-2-70B model using 3\*8\*A100(40G) and noticed that using any of the following codes will give an OOM situation at the beginning:

```
(1) WORLD_SIZE=24 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun \
--nproc_per_node=8 \
--master_addr=192.168.0.6 \
--master_port=9901 \
finetune_llama_ptuning.py

(2) python -m torch.distributed.launch \
    --nproc_per_node=8 \
    --nnodes=3 \
    --node_rank=0 \ # Change to 1, 2 on the other two machines.
    --master_addr=192.168.0.6 \
    --master_port=9901 \
    finetune_llama_ptuning.py

(3) deepspeed --num_gpus 8     --num_nodes 3     --master_addr 192.168.0.6     --master_port 9901     --hostfile /mnt/download/configs/hostfile.txt     finetune_llama_ptuning.py     --deepspeed /mnt/git/configs/deepspeed/deepspeed_zero2.json
```

Can I ask about the general configuration of the project's multi-node multi-gpu training command? I have tried to solve the OOM error I encountered before through collie, and I wish to get as close as possible to the official configuration as a way to get better results, as the OOM situation still exists at the moment, thanks a lot!

**Comment by KaiLv69** [comment]
Hi. Multi-node training is now supported by `slurm`. You can also run the `torchrun` command on every node to start multi-node training. 
The environment variables related to multi-node training are set here: https://github.com/OpenLMLab/collie/blob/1b54d1abb99203fd91ef2491feeecf8a8108b3c6/collie/utils/dist_utils.py#L129

**Comment by RickMeow** [comment]
I just noticed the `slurm` method.

This advice is very useful to me, thank you!
