### ISSUE TITLE
基于CoLLie训练7B Moss模型，无法使用Huggingface的AutoModelForCausalLM加载吗？

### ISSUE THREAD

**Issue by xuguohai** [OpenLMLab/collie#114]
从Huggingface下载[fnlp/moss-base-7b](https://huggingface.co/fnlp/moss-base-7b)，使用CoLLie中的MossForCausalLM类完成训练，保存的checkpoint无法再用Huggingface的AutoModelForCausalLM预测生成吗？

加载时会报错，提示
```
ValueError: The state dictionary of the model you are trying to load is corrupted. Are you sure it was properly saved?
```

请问如何解决？

**Comment by x54-729** [comment]
请问可以查看一下权重坐在文件夹的大小吗？这个报错看上去像是下载的文件不完整

**Comment by xuguohai** [comment]
我下载的模型[fnlp/moss-base-7b](https://huggingface.co/fnlp/moss-base-7b)没有问题，infer生成验证过是完整的。

然而基于CoLLie训练后，保存的模型，无法再用Huggingface加载会报错。

**Comment by xuguohai** [comment]
master分支有问题， 切换到dev分支可以了
