### ISSUE TITLE
ImportError: cannot import name 'PeftConfig' from 'peft.utils'

### ISSUE THREAD

**Issue by lisherlock** [OpenLMLab/collie#115]
谢谢您出色的工作！运行代码是出现：
2023-09-09 14:50:43,666] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
False
/home/a40-01/anaconda3/envs/py38/lib/python3.8/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'CUDASetup' object has no attribute 'cuda_available'
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from collie.config import CollieConfig
  File "/home/jdyy-a40-01/anaconda3/envs/py38/lib/python3.8/site-packages/collie/__init__.py", line 3, in <module>
    from .config import CollieConfig
  File "/home/jdyy-a40-01/anaconda3/envs/py38/lib/python3.8/site-packages/collie/config.py", line 6, in <module>
    from peft.utils import PeftConfig, PeftType

请问是cuda版本的问题吗？谢谢~

**Comment by KaiLv69** [comment]
你好，可以使用dev分支的代码。这里有个类似的issue: https://github.com/OpenLMLab/collie/issues/109

**Comment by lisherlock** [comment]
谢谢您的回复，这次可以工作了，但是出现了新的问题：
from transformers.deepspeed import _hf_deepspeed_config_weak_ref, HfDeepSpeedConfig, is_deepspeed_zero3_enabled
ImportError: cannot import name '_hf_deepspeed_config_weak_ref' from 'transformers.deepspeed'

我尝试过upgrade以及重新pip都不可以…

**Comment by KaiLv69** [comment]
你好，应该是类似的问题，我又对dev分支提交了一个commit，请再重新安装一下dev分支试试。

**Comment by lisherlock** [comment]
好的 谢谢您！

**Comment by 459737087** [comment]
还是这个问题啊 @KaiLv69

**Comment by KYLN24** [comment]
> transformers.deepspeed

你好，这应该是由上游仓库 API 的更改导致的。请问你在使用 dev 分支的 CoLLiE 吗？如果是的话，请贴一下具体的报错信息，这能帮助我们更快定位问题。如果不是的话，请先尝试安装 dev 分支。

**Comment by 459737087** [comment]
现在可以了，切换分支成功了 @KYLN24
