### ISSUE TITLE
ColumnParallelLinearWithoutBias is not supported by peft

### ISSUE THREAD

**Issue by JinchaoLove** [OpenLMLab/collie#116]
When using InternLM model with LoRA, with tensor parallelism degree `2`, it raised a ``ValueError: Target module ColumnParallelLinearWithoutBias() is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.``.

**Comment by KaiLv69** [comment]
Hi, LoRA is incompatible with TP. To both split model and use PEFT, ZeRO-3 and PP are supported.

**Comment by JinchaoLove** [comment]
> Hi, LoRA is incompatible with TP. To both split model and use PEFT, ZeRO-3 and PP are supported.

Got it! Thanks for the kind reply~

**Comment by JinchaoLove** [comment]
> Hi, LoRA is incompatible with TP. To both split model and use PEFT, ZeRO-3 and PP are supported.

In the function `setup_ds_engine` of `dist_utils.py`, it asserts both `pp_size=1` and `tp_size=1`, which means LoRA also not supports pipeline parallelism?

**Comment by KaiLv69** [comment]
This assertion actually checks whether the `CollieModel` is used when using TP or PP. I think LoRA should work well with PP.

**Comment by JinchaoLove** [comment]
> This assertion actually checks whether the `CollieModel` is used when using TP or PP. I think LoRA should work well with PP.

Got it! Many thanks!
