### ISSUE TITLE
该项目能否用于对模型进行二次预训练

### ISSUE THREAD

**Issue by Zheng-Jay** [OpenLMLab/collie#120]
感谢你们的开源贡献！
我想知道，本项目可以用于进行微调，那么能不能进行预训练呢？
我在文档看到本项目可以接受不带label的dataset，这是否意味着本项目已经实现了预训练？
如果是的话，具体应该怎么配置呢？

**Comment by KaiLv69** [comment]
你好，请问你的预训练场景相对于微调需要添加哪些方面的支持？

**Comment by Zheng-Jay** [comment]
就是能不能用未标注的数据集，使用lomo方法继续预训练呢？

**Comment by KYLN24** [comment]
你好！CoLLiE 可以用于模型的二次预训练，你可以在 further pretrain 阶段使用 LOMO 优化器。你只需要在构造 CollieDatasetForTraining 时传入仅包含 text 字段的字典列表即可。详情请参考我们的文档 https://openlmlab-collie.readthedocs.io/zh_CN/latest/api/generated/collie.data.CollieDatasetForTraining.html#collie.data.CollieDatasetForTraining

issue 就先 close 了，如果还有问题的话，欢迎 reopen 继续探讨~
