### ISSUE TITLE
Evaluating is too slow

### ISSUE THREAD

**Issue by JinchaoLove** [OpenLMLab/collie#121]
Hi, there. I find my evaluating stage is too slow, as shown in the below figure (training costs 1:43 for 10 steps, while evaluating already costs 3:43 for only 1 step). May I ask what may cause this kind of issue?

<img width="1011" alt="image" src="https://github.com/OpenLMLab/collie/assets/34153355/a507c792-8180-4f17-bf9f-1733f5f40cb8">

 The config and trainer are listed below (using the lasted `dev` branch):
```python
# CollieConfig
pp_size: 1
tp_size: 1
dp_size: 4
train_micro_batch_size: 4
eval_batch_size: 4
dataloader_num_workers: 4
eval_per_n_epochs: 1
eval_per_n_steps: 0
ds_config:
    train_micro_batch_size_per_gpu: 4
    zero_optimization:
        stage: 2
```

```python
# trainer
evaluators = [
    Evaluator(
        model=model,
        config=collie_cfg,
        dataset=dataset_val,
        collate_fn=data_collator,
        tokenizer=tokenizer,
        monitors=[
            EvalMonitor(collie_cfg)
        ],
    )
]
trainer = Trainer(
    config=collie_cfg,
    model=model,
    optimizer=optimizer,
    lr_scheduler=lr_scheduler,
    train_dataset=dataset_trn,
    train_dataset_collate_fn=data_collator,
    evaluators=evaluators,
)
```

**Comment by KaiLv69** [comment]
Hi, we have noticed this problem and are going to solve it. For now, you can set `model.set_cache(False)` right after the model is initialized. Hope it is helpful for you.

**Comment by KaiLv69** [comment]
新版本已解决
