### ISSUE TITLE
[Feature] examples 里是否可以新增一个 internLM的用例？

### ISSUE THREAD

**Issue by wuchangping** [OpenLMLab/collie#124]
看文档以及代码是存在 internLM的支持的，但是examples目录里缺少InternLm的用例

**Comment by KYLN24** [comment]
你好！CoLLiE 是支持 InternLM 的，其用法和 MOSS 等模型基本一致。请参考 examples/finetune_moss_for_training.py 或其他文件中里用例，稍作修改即可。
