### ISSUE TITLE
能不能重新训练啊？

### ISSUE THREAD

**Issue by 459737087** [OpenLMLab/collie#127]
可以重新训练吗，不用预训练的token,模型，自己重新生成一个模型。这样可以吗。

**Comment by 459737087** [comment]
还有一个问题就是，回答中有\<s>这是为什么


### \<s> 我是谁？

我是谁？

我是

**Comment by KYLN24** [comment]
CoLLiE 本身是支持从随机初始化的权重开始训练模型的
<s> 看上去可能是表示 begin of sequence 的 special token？可以贴一下具体的代码吗

**Comment by 459737087** [comment]
好的，谢谢，\<s>是打印在gradio上的，代码我也没看到。 @KYLN24
