### ISSUE TITLE
是否可以增加baichuan-2 的fine-tuning支持? 或者 是否可以给一个 如何 新增微调模型的guide？ 谢谢

### ISSUE THREAD

**Issue by wuchangping** [OpenLMLab/collie#130]
如题，谢谢！

baichuan-2: https://github.com/baichuan-inc/Baichuan2

或者 是否可以给一个 如何 新增微调模型的guide？ 用户有需求的话自己参考guide 添加

**Comment by KaiLv69** [comment]
您好，baichuan(-2)的结构与llama很相似，baichun-2-13B使用了ALiBi，应该可以从现在的llama里改过去。
添加模型的话，可以基于CollieModelForCausalLM，保持和llama里一样的接口就可以了。

**Comment by wuchangping** [comment]
谢谢

**Comment by KaiLv69** [comment]
collie支持HF上baichuan的zero-3，如果你有兴趣欢迎提一个添加baichuan collie model的pr :)
