### ISSUE TITLE
张量并行流水并行可以和lora一起使用么？报错ValueError: Target module ColumnParallelLinearWithoutBias() is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.

### ISSUE THREAD

**Issue by BlueSkyyyyyy** [OpenLMLab/collie#131]

**Comment by BlueSkyyyyyy** [comment]
完整代码如下：
`"""
一个使用CoLLie对LLaMA基座进行Prompt tuning的实例。
"""
import os
import sys
sys.path.append('../..')
import json
import torch

from transformers import LlamaTokenizer
# from transformers.generation.utils import GenerationConfig
from peft import get_peft_model

from collie.config import CollieConfig

from collie.data import CollieDatasetForTraining
from collie.data import CollieDataLoader

from collie.controller.trainer import Trainer
from collie.controller.evaluator import EvaluatorForPerplexity, EvaluatorForGeneration

from collie.models.llama.model import LlamaForCausalLM
from collie.utils.dist_utils import setup_distribution

from collie.utils.monitor import StepTimeMonitor, TGSMonitor, MemoryMonitor, LossMonitor, EvalMonitor
from collie.metrics import DecodeMetric, PPLMetric, BleuMetric
from collie.module import GPTLMLoss

from peft import (
    get_peft_config,
    get_peft_model,
    PromptTuningInit,
    PromptTuningConfig,
    TaskType,
    PromptEncoderConfig,
    PeftType
)
import torch.autograd.profiler as profiler

# from memory_profile import memory_profile
import sys
from collie.utils.peft_utils import load_peft
from peft import LoraConfig



#set trace for memory profile
# sys.settrace(memory_profile)

torch.cuda.memory._record_memory_history(True, record_context=True,
trace_alloc_max_entries=100000,
trace_alloc_record_context=True, device=0,
_enable_expensive_cpp=True)


# 1. 设置路径
# 1.1 预训练模型路径
pretrained_model = './Llama-2-70b-chat-hf'
# 1.2 Eval的decode结果保存路径
save_path = './result'

# 2. 设置配置
# 2.1 加载配置
config = CollieConfig.from_pretrained(pretrained_model)
# 2.2 添加配置
config.tp_size = 4
config.dp_size = 1
config.pp_size = 1
config.train_epochs = 1
config.train_micro_batch_size = 1
config.eval_batch_size =1
config.eval_per_n_steps = 100000
config.checkpointing = True
config.ptuning_checkpoint=None
#config.ptuning_checkpoint='./saved'


config.ds_config = {
    "fp16": {"enabled": True},
    "monitor_config": {
        "enabled": True,
        "tag": "sophia_alpaca",
        "csv_monitor": {
            "enabled": True,
            "output_path": "./ds_logs/"
        }
    }
}

# 3. 设置tokenizer
tokenizer = LlamaTokenizer.from_pretrained(pretrained_model, padding_side="left")

# 4. 加载数据集
train_dataset = [
    {
        'input': 'The movie is terrible. ',
        'output': 'Yes.'
    } for _ in range(5)
]
train_dataset = CollieDatasetForTraining(train_dataset, tokenizer)
eval_dataset = train_dataset[:32]

# 5. 加载预训练模型
model = LlamaForCausalLM.from_config(config)
# config.peft_config = PromptTuningConfig(
#     task_type = TaskType.CAUSAL_LM,
#     prompt_tuning_init = PromptTuningInit.TEXT,
#     num_virtual_tokens = 128,
#     token_dim = 4096,
#     num_attention_heads = 32,
#     num_layers = 80,
#     num_transformer_submodules = None,
#     prompt_tuning_init_text="Classify if the tweet is a complaint or not:",
#     tokenizer_name_or_path=pretrained_model
# )
config.peft_config = LoraConfig(
            task_type="CAUSAL_LM",
            r=8,
             lora_alpha=32,
             target_modules=["q_proj", "v_proj"],
             lora_dropout=0.05,
         )

model = get_peft_model(model, config.peft_config)

def count_parameters(model):
        return sum(p.numel() for p in model.parameters() if p.requires_grad)

for p in model.parameters():
    if p.requires_grad:
        print(p.name, p.data.shape)
print(model.print_trainable_parameters())

# 6. 设置优化器
## only with trainable pars

optimizer = torch.optim.Adam(filter(lambda p:p.requires_grad,model.parameters()), lr=2e-5)

# 7. 添加监视器
monitors = [
    StepTimeMonitor(config),
    TGSMonitor(config),
    MemoryMonitor(config),
    LossMonitor(config),
    EvalMonitor(config)
]

# 8. 添加Evaluator
evaluator_ppl = EvaluatorForPerplexity(
    model = model,
    config = config,
    dataset = eval_dataset,
    monitors = [
        EvalMonitor(config)
    ],
    metrics = {
        'ppl': PPLMetric()
    }
)
evaluator_decode = EvaluatorForGeneration(
    model = model,
    config = config,
    tokenizer = tokenizer,
    dataset = eval_dataset,
    monitors = [
        EvalMonitor(config)
    ],
    metrics = {
        'decode': DecodeMetric(save_to_file = True, save_path = save_path)
    }

)

# 9. 实例化trainer
trainer = Trainer(
    model = model,
    config = config,
    loss_fn = GPTLMLoss(-100),
    optimizer = optimizer,
    train_dataset = train_dataset,
    monitors = monitors,
    evaluators = [evaluator_ppl, evaluator_decode]
)
if config.ptuning_checkpoint is not None:
    trainer.load_peft(path="./saved",mode="model")
# 10. 训练/验证
trainer.train()


#trainer.save_checkpoint(path="./", mode="model")
trainer.save_peft(path="./ptuning", mode="model")
snapshot = torch.cuda.memory._snapshot()
rank = torch.distributed.get_rank()
from pickle import dump
with open(str(rank)+'snapshot.pickle', 'wb') as f:
    dump(snapshot, f)
#  Command CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --rdzv_backend=c10d --rdzv_endpoint=localhost:29402 --nnodes=1 --nproc_per_node=4 finetune_llama_prompt_tuning.py
`

报错：
Traceback (most recent call last):
  File "finetune_llama_lora.py", line 138, in <module>
    model = get_peft_model(model, config.peft_config)
  File "/usr/local/lib/python3.8/dist-packages/peft/mapping.py", line 106, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 889, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 111, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/lora.py", line 274, in __init__
    super().__init__(model, config, adapter_name)
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/tuners_utils.py", line 88, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/tuners_utils.py", line 219, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optionnal_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/lora.py", line 372, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peft/tuners/lora.py", line 481, in _create_new_module
    raise ValueError(
ValueError: Target module ColumnParallelLinearWithoutBias() is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.

**Comment by KaiLv69** [comment]
lora还不支持和张量并行一起使用。Same issue: https://github.com/OpenLMLab/collie/issues/116

**Comment by BlueSkyyyyyy** [comment]
> lora还不支持和张量并行一起使用。Same issue: #116

谢谢！
