### ISSUE TITLE
__init__() missing 'init_method' and 'config'

### ISSUE THREAD

**Issue by yueg-security** [OpenLMLab/collie#133]
base_model: llama-7b
运行方式：CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --nproc_per_node=4 train.py（adalomo目录下的train.py文件）

在使用collie LlamaForCausalLM加载模型时，deepspeed的parttion_parameters.py文件报错如下：
__init__() missing 2 required keyword-only arguments: 'init_method' and 'config'

**Comment by KaiLv69** [comment]
你好，可以安装0.2.0版本的megatron FYI：https://github.com/OpenLMLab/collie/issues/126
