### ISSUE TITLE
是否可以新增chatglm3 支持？

### ISSUE THREAD

**Issue by helloaigc** [OpenLMLab/collie#134]
如题，chatglm3 已放出

https://github.com/THUDM/ChatGLM3

**Comment by KYLN24** [comment]
ChatGLM 3 和 2 的模型结构似乎是完全一样的？

**Comment by helloaigc** [comment]
不懂哦，不然我这边就给提个PR了。。。。

**Comment by helloaigc** [comment]
看代码 CHATGLM3 vs CHATGLM2 ，只增加了 多伦对话。其他都没动
