### ISSUE TITLE
chatGLM2 使用张量并行报错

### ISSUE THREAD

**Issue by BlueSkyyyyyy** [OpenLMLab/collie#135]
dev分支：
collie/examples/finetune_chatglm2_for_summary.py
配置：
config.pp_size = 1
config.tp_size = 8
报错：
Traceback (most recent call last):
  File "finetune_chatglm2_for_summary.py", line 81, in <module>
    model = ChatGLM2ForCausalLM.from_pretrained(args.model_path, config=config)
  File "/home/sse-ard/merlin.xie/proj/dev/collie/collie/models/base.py", line 332, in from_pretrained
    set_module_tensor_to_device(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([65024, 4096]) in "weight" (which has shape torch.Size([8128, 4096])), this look incorrect.

**Comment by KaiLv69** [comment]
你好，chatglm2因为有grouped_query_attention且组数为2，所以tp_size最高只能是2

**Comment by BlueSkyyyyyy** [comment]
> 你好，chatglm2因为有grouped_query_attention且组数为2，所以tp_size最高只能是2

2好像也不行；
我设置为：
config.pp_size = 1
config.tp_size = 2
报错：
Traceback (most recent call last):
  File "finetune_chatglm2_for_summary.py", line 81, in <module>
    model = ChatGLM2ForCausalLM.from_pretrained(args.model_path, config=config)
  File "/home/sse-ard/merlin.xie/proj/dev/collie/collie/models/base.py", line 332, in from_pretrained
    set_module_tensor_to_device(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([65024, 4096]) in "weight" (which has shape torch.Size([32512, 4096])), this look incorrect.

**Comment by KaiLv69** [comment]
这个问题我们在kv_cache解决了但是还没merge进dev。在dev上commit了一下，最新版dev应该可以了。FYI: https://github.com/OpenLMLab/collie/commit/a75dfc4b545612eb5e01d18501243d5070942375

**Comment by BlueSkyyyyyy** [comment]
> 这个问题我们在kv_cache解决了但是还没merge进dev。在dev上commit了一下，最新版dev应该可以了。FYI: [a75dfc4](https://github.com/OpenLMLab/collie/commit/a75dfc4b545612eb5e01d18501243d5070942375)

谢谢您及时的回复！！我用的dev分支。
还有一个地方应该也要修改:
collie/collie/models/chatglm2/model.py:204行  class CoreAttention.forward  if pytorch_major_version >= 2: 分支：
new_context_layer_shape = context_layer.size()[:-2] + (
                self.hidden_size_per_partition,
            )
修改为：
new_context_layer_shape = context_layer.size()[:-2] + (
                self.hidden_size_per_partition // self.config.tp_size,
            )
修改之后试了一下推理，config.tp_size = 2 config.pp_size = 1可以正常运行；但是config.tp_size = 2 config.pp_size = 4 报错：
File "/home/sse-ard/merlin.xie/proj/dev/collie_kv_cache/collie/collie/models/base.py", line 339, in from_pretrained
    assert param.data.shape == state_dict[name].data.shape, f"The shape of the parameter corresponding to the `{name}` does not match: {param.data.shape} vs {state_dict[name].data.shape}"
AssertionError: The shape of the parameter corresponding to the `30.weight` does not match: torch.Size([32512, 4096]) vs torch.Size([65024, 4096])
发现是原ckpt的lm命名是output_layer，因此我把need_column_list 添加了之前的 “output_layer.weight”。
修改之后可以运行。

**Comment by KaiLv69** [comment]
> > 这个问题我们在kv_cache解决了但是还没merge进dev。在dev上commit了一下，最新版dev应该可以了。FYI: [a75dfc4](https://github.com/OpenLMLab/collie/commit/a75dfc4b545612eb5e01d18501243d5070942375)
> 
> 谢谢您及时的回复！！我用的dev分支。 还有一个地方应该也要修改: collie/collie/models/chatglm2/model.py:204行 class CoreAttention.forward if pytorch_major_version >= 2: 分支： new_context_layer_shape = context_layer.size()[:-2] + ( self.hidden_size_per_partition, ) 修改为： new_context_layer_shape = context_layer.size()[:-2] + ( self.hidden_size_per_partition // self.config.tp_size, ) 修改之后试了一下推理，config.tp_size = 2 config.pp_size = 1可以正常运行；但是config.tp_size = 2 config.pp_size = 4 报错： File "/home/sse-ard/merlin.xie/proj/dev/collie_kv_cache/collie/collie/models/base.py", line 339, in from_pretrained assert param.data.shape == state_dict[name].data.shape, f"The shape of the parameter corresponding to the `{name}` does not match: {param.data.shape} vs {state_dict[name].data.shape}" AssertionError: The shape of the parameter corresponding to the `30.weight` does not match: torch.Size([32512, 4096]) vs torch.Size([65024, 4096]) 发现是原ckpt的lm命名是output_layer，因此我把need_column_list 添加了之前的 “output_layer.weight”。 修改之后可以运行。

谢谢你的反馈 :)

**Comment by KaiLv69** [comment]
新版本已解决
