### ISSUE TITLE
除了设置checkpointing之外，dp+tp+pp下，还有什么方式可以降低显存消耗？

### ISSUE THREAD

**Issue by tongjizzy** [OpenLMLab/collie#64]
我这边在使用dp+tp+pp模式跑llama-65b模型，80张V100卡，tp_size=4，pp_size=20，dp=1，载入完model+optimizer后，一张卡大约要消耗15GB显存，然后我这边设置batch_size=2，gradient_accumulation_steps=160。batch_size已经很小了，但是开始训练后，最大的一张卡显存消耗到了30GB，就算将checkpointing设置为true，也要28GB显存，感觉单纯的activation应该不至于消耗这么多显存吧。这使得我没有办法把batch_size提上去，GPU的空泡率有点高，速度比单纯的zero stage3更慢了。
所以我想问一下，有没有什么什么办法可以进一步降低一下显存占用？

**Comment by 00INDEX** [comment]
@tongjizzy 当采用pipeline并行的时候，真正的batch size就等于train_micro_batch_size*gradient_accumulation_steps（https://arxiv.org/abs/2104.04473）。因此您可以尝试降低gradient_accumulation_steps，以此降低真正的batch size。
而且当采用pipeline并行的时候，train_micro_batch_size一般设置为1来达到最好的并行效果。

**Comment by tongjizzy** [comment]
我观察到在使用pipeline parallel的时候，最后一个stage所在的显卡，显存占用明显要比其他的高，这部分主要是哪部分的占用呢？这个有办法可以降低吗？

**Comment by KaiLv69** [comment]
> 我观察到在使用pipeline parallel的时候，最后一个stage所在的显卡，显存占用明显要比其他的高，这部分主要是哪部分的占用呢？这个有办法可以降低吗？

现在默认的切分算法会尽量平均每个stage中参数的数量。第一个stage和最后一个stage除了attention层之外还会含有embedding层和lm_head层，所以显存占用会多些。
