### ISSUE TITLE
项目readme里面说的A100是多少G版本的。

### ISSUE THREAD

**Issue by ArtificialZeng** [OpenLMLab/collie#66]
在使用Adam优化器的情况下，各个模型需要的最少的GPU（A100）数量

**Comment by KaiLv69** [comment]
你好，是80G版本的。

**Comment by ArtificialZeng** [comment]
> 你好，是80G版本的。

感谢回复！
根据您的论文《Full Parameter Fine-tuning for Large Language Models with Limited Resources》，全参数微调最低是8*24=192G显存，这就是最低的全参数微调显存要求对吗？  还有没有可能更低？？

**Comment by KaiLv69** [comment]
使用 LOMO 训练 65B 的 model 时需要 8 * RTX 3090，此时显存大部分被 parameters 占用，占用量与仅仅 forward 相差不多。如果显存还是不够用，可以考虑1. 降低模型参数量；2. 同时使用量化技术。
