### ISSUE TITLE
bf16是否支持？

### ISSUE THREAD

**Issue by lw3259111** [OpenLMLab/collie#70]

**Comment by KaiLv69** [comment]
支持，可以这样设置
```python
config.ds_config = {
    "bf16": {"enabled": True},
}
```

**Comment by lw3259111** [comment]
@KaiLv69 
我的ds_config是
```json
config.ds_config = {
        "bf16": {
            "enabled": True
        },
        "zero_allow_untested_optimizer": True,
        "zero_force_ds_cpu_optimizer": False,
        "zero_optimization": {
            "stage": 3,
            "offload_optimizer": {
                "device": "cpu",
                "pin_memory": False
            }
        }
}
```
报错：
`RuntimeError: output tensor must have the same type as input tensor`
<img width="711" alt="image" src="https://github.com/OpenLMLab/collie/assets/12690488/d3c0d9fa-f62e-4a61-b102-a5e824d3b999">

**Comment by KaiLv69** [comment]
你好。你的PyTorch版本是2.0吗？可以尝试调低PyTorch版本。应该是DeepSpeed的问题，可以参考这个回复https://github.com/microsoft/DeepSpeed/issues/3654#issuecomment-1625600804

**Comment by lw3259111** [comment]
@KaiLv69 
好像是lomo优化器问题，torch.optim.AdamW是支持bf16的

**Comment by KaiLv69** [comment]
你可以尝试一下这个pr里的代码：https://github.com/OpenLMLab/collie/pull/74。
