### ISSUE TITLE
llama在张量并行模式下的attention score计算是否有问题？

### ISSUE THREAD

**Issue by tongjizzy** [OpenLMLab/collie#77]
我这边看代码里面，llama的attention score的计算是直接用的query乘以key，但是在张量并行的模式下，query和key应该都已经被切分了把。这里直接相乘的话，得到的attention score并不是在完整的query和key上进行的，这是否不太对？
希望大佬能给解答一下！

**Comment by Carol-gutianle** [comment]
你好，切分发生在不同的head之间，head之间的注意力计算本身就是独立的，所以attention score不会受到切分的影响。

**Comment by tongjizzy** [comment]
哦哦，明白了。谢谢！
