### ISSUE TITLE
是否可以增加 LLAMA2的支持？谢谢

### ISSUE THREAD

**Issue by helloaigc** [OpenLMLab/collie#88]
如题，
LLAMA2: https://github.com/facebookresearch/llama

**Comment by x54-729** [comment]
感谢关注！llama2 的支持工作我们已经在推进了~

**Comment by helloaigc** [comment]
Thanks

**Comment by x54-729** [comment]
目前 dev 分支已经更新了 llama2 的结构，您可以试用下看看，如果有bug欢迎您随时指出~
