### ISSUE TITLE
请教 DEV分支的这个改动 ：support llama2 ，llama-2和llama-1可以同时都支持么？

### ISSUE THREAD

**Issue by helloaigc** [OpenLMLab/collie#89]
请教 DEV分支的这个改动 ：support llama2 ：
`https://github.com/OpenLMLab/collie/commit/5adf2a368dcb107ef5685057c0380eeaad10c1a2`

llama-2和llama-1可以同时都支持么？ 作为用户我们比较期望能同时都支持。

**Comment by x54-729** [comment]
是的，llama和llama2都可以使用

**Comment by helloaigc** [comment]
> 是的，llama和llama2都可以使用

多谢

**Comment by kaiwang13** [comment]
70B因为使用了GQA所以无法正确加载，参考https://github.com/facebookresearch/llama/issues/384，希望可以添加LLaMA2-70B的支持
